
development:
  adapter: postgresql
  encoding: unicode
  database: breakfast_app_development
  pool: 5
  username: scottsMac
  password:
  host: localhost

# he same as development or production.
# test:
#   adapter: postgresql
#   encoding: unicode
#   database: breakfast_app_test
#   pool: 5
#   username: francescawedemeyer
#   password:

# production:
#   adapter: postgresql
#   encoding: unicode
#   database: breakfast_app_production
#   pool: 5
#   username: francescawedemeyer
#   password:

